export const privacyContent = `
# Privacy Policy

Last Updated: February 12, 2025

## Introduction
Perfect Reply ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our Chrome extension.

## Information Collection
Perfect Reply is designed with privacy at its core. We:
- Do not collect or store your messages
- Do not track your browsing activity
- Process all data locally on your device
- Do not share any information with third parties

### Information You Provide
- Email address (for account creation only)
- User preferences (stored locally on your device)

### Technical Information
- Basic extension usage statistics
- Error logs (for troubleshooting)

## Data Storage
All message content and preferences are stored locally on your device using Chrome's storage API. We do not maintain any central database of user communications.

## Security
We implement security measures to protect your information:
- Local data processing
- Encrypted communications
- Secure authentication system

## User Rights
You have the right to:
- Access your stored information
- Delete your account
- Export your data
- Modify your preferences

## Contact
For privacy-related questions, contact us at: privacy@perfectreply.com
`;

export const termsContent = `
# Terms of Service

Last Updated: February 12, 2025

## 1. Acceptance of Terms
By installing and using Perfect Reply ("the Extension"), you agree to these Terms of Service.

## 2. Description of Service
Perfect Reply is a Chrome extension that helps users craft professional workplace communications.

## 3. User Responsibilities
You agree to:
- Provide accurate registration information
- Maintain the security of your account
- Use the Extension in compliance with all applicable laws
- Not attempt to reverse engineer the Extension

## 4. Intellectual Property
- The Extension and its original content are our intellectual property
- Users retain all rights to their message content

## 5. Limitation of Liability
We provide the Extension "as is" without warranties. We are not liable for:
- Message content generated by users
- Consequences of using suggested responses
- Service interruptions

## 6. Changes to Terms
We may modify these terms with notice to users.
`;

export const refundContent = `
# Refund Policy

Last Updated: February 12, 2025

## Refund Eligibility
- Full refund available within 14 days of purchase
- Must not have violated Terms of Service
- One refund per user

## Refund Process
1. Submit refund request via email
2. Include purchase confirmation
3. Provide reason for refund (optional)
4. Processing time: 5-7 business days

## Non-Refundable Cases
- After 14-day period
- Violation of Terms of Service
- Multiple refund attempts
- Account misuse

## Contact for Refunds
Email: refunds@perfectreply.com
`;